#!/bin/sh
# postinst script for libsimplesocketpp
#
# see: dh_installdeb(1)

set -e

case "$1" in

	remove|purge)
		rm -f /usr/lib/libsimplesocket++.so.0
		rm -f /usr/lib/libsimplesocket++.so
	;;

	abort-purge|abort-remove|abort-deconfigure)
		exit 0
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;

esac

exit 0
