#!/bin/sh
# postinst script for libsimplesocketpp
#
# see: dh_installdeb(1)

set -e

case "$1" in

	configure|install)
		ln -s libsimplesocket++.so.0.0 /usr/lib/libsimplesocket++.so.0
		ln -s libsimplesocket++.so.0.0 /usr/lib/libsimplesocket++.so
	;;

	upgrade|abort-upgrade|abort-install|abort-configure)
		exit 0
	;;

	*)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 1
	;;

esac

exit 0
